A munkacsoportok áttekintése.

Rendszeresen szánjunk rá időt, hogy

Andris elkezdte a vízpótlásos esettanulmányokat.

I/1 Hidrológia, modellezés és adatelőkészítés.
I/2 Távérzékelési adatok.

Jövő héten I/1 munkacsoport megbeszélés.
Gábor mégis beírjuk. De csak a nevét.

* Gazdasági rész
Számlák átkönyvelése, van egy alap szerződés.

Szerződés hallgatói alap.

Munkaköri leírás is megy.

Személyi tervezés. Zolival Péter.

Átkönyvelési kérelem havi szinten kérni.

** Móni
Kérik a költségvetés részletezését.

Word leírás, amit benyújtottunk. Kérik a Wordben a költségtervben sorok mit jelentenek.
Munkabérnél hány fő bevonása. Kutató, Herceg András, létszámra legyen meg.
Három hallgatól

Mindent precízen. Móni úgy várja a pályázati előírásokat, mehet, nem mehet.
Hasznos négyzetméter alátámasztás. 10-15 számlát megkapjuk.

Átküldi, hogy bontsuk alá.

Beruházás ne legyen, talajnedvesség mérő beszerzése. Kutatásra szükséges eszköz.
Ha beírjuk konkrétan pl. három számítógépet, nem veszed, számon kérik.

Költségvetést úgy megbontani, hogy oda kerüljön, ahová tartozik.
ERTI csak bér! Miénk x mio ővék z mio.

ERTI megküldi az összesítőt. Ők indítják a folyamatot. Más kötelezettség nincs
az ERTI felé.

** Zoli
Ne legyen lebontva a dologi, hanem soroljuk fel! Egyelőre részletezzük le, ne legyen
csak a költségsor összege.

Talajnedvességmérők beszerzése helyett kutatási eszközök beszerzése.
Számítástechnikai eszközök.

Összeget küldi amit már megbeszéltek.

Tímea 11.15 ér rá.

* Csoportok folytatása
** I/2. Távérzékelési rész

Géza, Botond, Bence.
Gábor csak tanácsot ad.

** II Vízvissza aktív
Itt a kettő és inkább egybe.

Kaszó, Puskás Lajos, Somogy.

Kornél-Áron-Tomi

Utasok (Primusz P, KisfaludiB) Herceg Andris
