* Lantos Avar Tamás projekt egyeztetés
Gribovszki Zoltán ismerteti a projektfeladatot.

Hidegvíz-völgyi mérés, kis kísérlet beállítása. Valós mérés.

Erről már beszéltek a múlt héten.

Agrárerdészet is tetszik neki. 10 kredit diploma és 20 kredit kutatás.

Erdőgazdaságot bevonni?

Egy kapcsolattartót kijelölni. Ki ér rá legjobban? Balázs.

Első bejárást közösen kellene. Primusz Péter szerint a hallgató tudjon
önjáróan dolgozni. Mi lenne a mérés? Mi legyen a mérés. Először
geodézia, domborzat modell és térkép. Hol van áteresz és
vízátvezetés. Kézi GNSS, fénykép. Megnézi a felületmodellt. Melyik
hely lenne a jó.

Kucsara Mihály tanulmányából becslést csinálhatna. Nem lesz mindenütt
mérés. így működik, ilyen károk. TDK nem tud mérésre támaszkodni.

Az útra eső csapadékból mennyi jut el a mederbe? A Farkas-árokban
a bejutás esélye nulla.

Mi a hely? Lehet csőáteresztő, vagy a földút árka. Vízterelőt
berakunk, a végén Thomson és nyomásszonda. Kitelepítnei. Nem lehet
elérni a nagy esőt. Esetleg tartós eső.

Előkészíteni a terepet. Lehet egy-két mérési nap lesz. Domborzatnak a
térinformatikai elemzése az úthálózattal összefüggésben. Hidrológiai
elemzés. Mi az ami lejöhet? Egy-két hely, mennyi lehetne ott,
következő időszakban validálni.

Augusztus végén van a projekt zárás. Talán beleesik egy víz.

A hallgatónak legyen valami, amire aláírást lehet adni, még a TDK-ig
lehet finomítani. A mérésekből összefüggésből kellene dolgozni
először.

Ütemezés. 15 hét áll a rendelkezésére. Havi ütemezés beszámolás. Első
héten beszámoló leadása, bemutató megtartása.

Vizsgaidőszakban három vizsga van.

Kutatási tervet el kell készíteni. ERFAretes anyagot odaadná
Avarnak. 80 oldal. Január elejéig kialakul egy koncepció.

Koncepció; irodalmazás, terepbejárás, térinformatikai
elemzés. Hozzárendelné a napokat. Kutatási terv kell és szerződést
kell kötni a TAEGgel.

Jövő héten be kellene jönnie. Hétfőn délután.

Szerződést kell kötni a TAEGgel. Mennyire kell szorosan venni? Eddig
csak igényfelmérés volt.

Folcz Ádámmal kapcsolat, ne fogjunk nagyot. Ádámmal egyeztetni.  Jó
ötletnek tartja. Munkáját segítenék. A mérés helyét keresnénk meg
először.  Hallgatói 8. szemeszteres projekt. Tervezést megelőző
projekt. Keresné a helyét, hogy hol lehetne. Egy monitoringot
beállítana. Fogalmunk sincs mennyi folyik le, ehhez alapozó tanulmány.
Síkvidéken csinálják, a hegynek külön örül. Elmossa a patak mellett az
utak mellett. Nem hozzá kellene húznia. Erdészet kollégáit
mozgatni. Köveskuti Zoli vagy Preiczinger Márk.

A Kucsara anyagot átküldte korábban. Erfaret tanulmány november 4.
12-es anyag. Letölti és továbbítja. Jövő alkalomra átnézni.
Mértékadó csapadék lényeges

Email:
LantosAT22@student.uni-sopron.hu
