* Agrárminisztérium szerkezete
Két téma:
** Vízháztartási modellezés
Távérzékelési adat is.

*** Hidrológiai modellezés és adatelőkészítés
Hidegvízvölgyi és botankerti adatok.
Vezető Kati, K. Péter, Lili,
Bence, András, Zoli

Adatbázis rendberakás, hőmérséklet, csapadék.

ERTI válasszanak ki jellemző állományt. Konzultációs jelleg.

*** Távérzékelési rész
Párolgás, levélfelület.
Péter fogja össze.
Géza, Botond, Gábor, Bence

** Vízvisszatartást javító aktív beavatkozások
*** Feltáró hálózathoz és egyéb vízvisszatartás
Minden, ami feltáróhálózathoz kapcsolódik. Tapasztalatok és javaslatok.
P. Péter, Balázs, Andris
Akinek van kapacitása vezeti.
Konkrét mintaterület kijelölése, ha lehet a TAEG területén.

Témája irodalmazás és esettanulmány meglátogatása.
Tározók, medertározás, fennékküszöb. Tapasztalatok és javaslatok.
Terepi megtekintése.

Andris vezeti.
Zoli, Péter, Tomi.
Bence, András

*** Geoinformatikai
Holvan és fényképek hozzákapcsolása, Adatbázis létrehozása.
Részletes nem lehet. Dokumentációk és helyek összefogása

Kornél, Áron, Tomi, Andris, Zoli, Péter

* Kommunikálás
Jövő héten intézetin egyeztetni. Kati, Andris gyakorlatot kezdi, ha addig nem végzünk.
