* Zolival
** Rendszeres megbeszélések.
*** Csop 1
- Géza Szakért. Képegyeztetést mondja el ezeken az adatokon.
- Botond Repülést csinálja és elmondja, hogy hogyan csinálja,
  elmagyarázza a feldolgozást.
- Bence irodalmazást csinál a doglokról. Koordináták megvannak,
  jelentés, milyen forrás, Koordináták vigye fel és térkép.
- Brolly Gábor Tegnap beszéltünk, önállóan csinálja Kamilla diplomamunkáját,
  Koronavetületek és objektumok.
*** Csop 2
- Tomi Mérnökgeo2 patakszakasz felmérése és
  ledokumentálása. (Esetleg Egererdőhöz eljön.)
- Áron Térinfómenedzsment, patak egyéb Kaszó, Békés projektet
  csinálnak és egy-két vízpótlásról születik termék.
- Kornél Topográfia, mit oktat és felületmodellen milyen elemzések
  lehetnek vízügyi szempontból. Összefoglaló óra, amit Andris
  felvesz. Hogy dolgoznak a felületmoddellen. Lantos Avart is meg lehet hívni. Foglalja össze!
- Andris

*** Csop 3
Utas

Tárgyat kiírtak Primuszék. Avarral dolgoznak.

Kiírtak egy régi kódú tárgyat amit felvesz. 8 hallgató fel is vette.x

Feladatokat kiadnak, úthibák és műszaki létesítmények állapotértékelése QGIS adatbázis.

Avart Primusz Péter érdekli, de Balázs a fő.

Primusz küldött vízpótlásos cikket.

Andris írt irodalmazást, ami az akadémiai ülésre jó. Konferencián előadott cikk. Át kell nézni
a munkáját. Belefutott szakkifejezésekre.

Le kell osztani, határidőket osztani és számonkérni. Effektív anyag legyen.

Embereknek ettől függ a megélhetése.

** Mérnökgeodészia
