* Megbeszélés Gáborral

Korona hol van, és mekkora, törzsi lefolyás.

Földi szkennelésből látszik-e, hogy hol van adat?
Kádak hol vannak?

Érdemes összerakni. Mit jelent, hogy hol vannak a koronák?

Fehér Balázs alaptérképe, objektumok helye és a vargyűjtők. Ezeknek a pontos helye,
illetve a törzsek helye, illetve koronáról információ.

Az egyik többet gyűjt, mint a másik kettő. 10 cm-t kiállnak. A korona
fölötte mennyire sűrű. Egy relatív számot mondani.

Korona sűrűségről nehéz mondani vallamit, miniél beljebb annál
kevesebb pont, akár felülről, akár alulról.

Ágak vannak, tűlevelek mennyire sűrűk. Relatív számot mondanak rá, Kamilla
kikísérletezi. A földön is van még keret.

** Bükkös
Réttől a határsávig a sokszuög, egy lappont bentvan. 3-4 szakaszos.
Aknától a határsávig. Bódis Virág Berenikével volt Gézának mérése.

Volt lent három talajkaró a Tomi és Gábor mérése.

** Tomi
Kézi szkenner.

* Lengyel Judit
2025 szeptmbertől 26 augusztusig.

Lengyel Judit feladatokat szeretne.

Bérbeszámítás indult:
Munkabér költség:
11 mio 630. Kollégák is be legyenek vonva.

** Bérbeszámítás
*** Első szakasz
Munka kezdete, amit alapból csinálunk.
Kutatástervezés. Alapadatgyűjtés.
Szakiroldalmazás.

Tímea általános adminisztráció.

- Brolly Gábor Földi lézerszkennelés 2025 szepteber
- Gribovszki
- Horváth Tímea
- Kisfaludi Balázs
- Zagyvainé Kiss Katalin
- Kalicz Péter én XII.ig!

Bérbeszámítás XI. 30-ig bérbeszámítás

Kalicz végig! ERTI nincs külön költségvetés.
Gazdasági munkatársak nem lettek bevonva.
Mi vittük el a bérbeszámítást. Csak többlet
lesz!

Géza OTKA-ba nem lesz bevonva!

Balázs utakkal kapcsolatos vízvisszatartási megoldások gyűjtése, irodalmazás.

Bérbeszámításra volt 3mio 881Ft Szocho kedvezmény Katinak.

Töblet kétszerese 7mi 750-et szétosztjuk.

Valakinek a maradványt ki kell fizetni! Kornél az összes
maradványt megkapja.

*** Második szakasz

Febr 1.-el indítjuk

Nálam január!

** Leírás
Oktató, kutatás, vízelnyelők.

Aktív javító intézkedés

Kutatás alap. Publikáció bérbeszámítás.

A modell és lépések többlet. Lépések.
Ami nem a publikáció, kutatás, oktatás.

** Agrárminisztérium folytatás
Szerződéskötés folyamatban.
Logikai bukfenc ne legyen benne.
Erdőmérnök nézi.

** Zárás
Mielőtt az egész zárul. Össze kell ülni. Július elején!

Bárki maradhat egy hónapban, Többet osztani.

Kornél keret és súlyokat készít.
Többletet oszt! 2-szeres súly!

Kornél melyik az a projekt, amibe nincs benne?

4+7 emberközött

Projektmunka a hallgatókkal.

Július 31-ig kifut.


Jelentés összeállítása.

** Interreg
Walter Kati.
Van keret bőven. Adminisztratív teher nagy.

Vezető partner, stratégiai partner.

Február 26. Együtt kell menedzselni. Szakmai program megvan.
Visszaküldött kérdést. Tök jó van pénz a programrészen, van űrlap,
amit visszaküldött Andrásnak. Be lehet adni egyeztetés nélkül. Minél
korábban tudnak róla annál nagyobb esély a nyerésre.

Űrlapot töltsük ki. Technishe Universitate. Vezetőpartner,
és startégiai partnerek. Erdőgazdaságok. Online
konferencia, becsatlakoznak.

- TU
- mi

- Startégiai partnerek:
  - VERGA
  - TAEG

Vezetőpartnerség, nekik kell a projektszintű beszámolót
összeállítani. Plusz munka. Projekt szintű pénzügyi és szakmai
jelentés.

*** Program vége
Következő programozási időszak 27-ben futnak ki.
Bécsieknél lehetnek jó pénzek. 60-70 EUR/óra.

Koncepciót vállalhatják. Agrárkutató vállalja-e?

Forschung Burgerland Bidló Peitschip Michael.

Egy csomó rész ismétlődik. Chat GTP fordítás és lektorálják.

Az űrlap. Emlékeztető a megbeszélés, zoom meeting.

Regionális koordinátor véleményezi, akkor a bécsinél
is véleményeztetni kell.

Alsó-Ausztriában egy csomó pénz van!

Személyi költség 40% általában utazás, buszköltség,
konferencia.

Csak bérbeszámítás lehet.

márciusban beadjuk, szeptember, október, januárral indul.
28 végéig tud futni.

24+2-3 hónap.

Vezetőpartnerséget vállaják és jól meg tudjuk csinálni,
akkor.

*** Széles Bori
Intercepciós kert kialakítása.

Interreg van tapasztalat. Vizes témában van pénz.

Völgytalp erdőállomány mintaterület kialakítása. Demonstrációs
bemutatás, adat elemzés.

Miért jó a társadalomnak, kormányzati szerveknek?
