* Mónika
Szám: F115 (GKI)

Külön az ERTI-nek.

Projektek kapcsán élhetnek ezzel a rendszerrel.

Határidőket nem bírta Móni. Átlállásnál a főigazgatóság segít.
Dékániban betaítanak emberekt, és próbálják pótoli.

Alapkoncepcióval egyetért Balint, hogy szétbontva.

Rezsi számlákat dékáni átveszi. Központilag megoldanák. Plusz feladatok beépítve
többletbéreket beépítik.

Dékán szeretné, ha innen menne ki minden fluenta! Egyes folyamatok nem valósulnak meg.
Beszerzések nem valósulnak be.

Beszerzési tervnél személyi felelőst kell határozni. Aki szakmailag a
véleményezésnél rövid határidőre megtenni. Szakmailag legyen ember,
aki érdi. Intézet mondjon véleményt.

Szakmai specifikáció ellenőrzse. Szakmailag kell, akkor meg legyen fogalmazva.
Kutatási asszistens szervezheti. Egy projektnél egy ember összeszedheti.

Szakmai megfogalmazás minél hamarabb legyen meg! Szakmai előrelépés legyen benne!

Szeptember 30-ig kell elszámolni. Minden számlának a végéig aug 30-ig beérkezni
zárásig mindent kiegyenlíteni. Béreket addig lezárni. Hó közepén járulákkifizetés,
ezért az utolsó hónapra ne tervezzünk személyi költséget. Minden személyügyre.

Hó közepén járulék utalás miatt júli 31-ig lezáródjon minden. Szakmai
beszámoló és összesítő a költségvetésről. Szamai anyag és ellenőrzésre
15 tételt, amit kiválasztanak. 15 számlát bekérnek random. Akkor beküldik
az alátámasztó dokumentumot.

** Beszerzés
Hamar indítani. Minden tételt szakmailag alátámasztani.
15 mio a közbeszerzési értékhatár. Belefér a három árajánlatosba.

Csak egy cégtől, pontos precíz leírás, hogy miért pont az a partner és
kizárólagossági nyilatkozat. Nincs olyan nagy külöbség. Géza és Zoli is tudja,
ő.

Beruházás várható, hogy kiválasztják.

Bérráterhelés a teljes bér 33%-a. Többlet 67%. bérráterheléses feladat
nem lehet ugyan az, mint a többlet. Ne legyen egy időszak. Különüljön el
a feladat és az időszak. Ne legyen a kettő között különbség.

Szeptember 1-től végezhetem a feladatot. Szeptember hónapot be lehet tenni.

Bidló erdőrezervátum alapján teljes időszakot nem szoktuk átfedni az időszakkal.
Bérátemelés 2 hó, a többlet meg 4 hó.

Bérráterhelés munkaköri leírás, többletekre határozatot és teljesítés
igazolást segíteni.  Személyi kölstéeknél szabaság és táppénz nem
elszámolható. Csak a szabasággal csökkentett. Elcsúszik a tervezés.
Két hónapot javasolt. Dékán úr Bidlóéknak engedi, hogy a feladat elvégzése
előtt.

Dékán úrral egyeztetni, hogy a többletet, hogyan? Egy összeg jó egy ember egy sor.
Szakmai feladatot hozzárendelni a személyi költséghez. Szakmai munka nem
feltétlenül valós időben.

Kiküldetés hasonló a TKP-hoz hasonlóan.

Küld a Timinek elszámolási útmutatót. Az Agrárminisztérium adja.

Jégkaparót kivették, csak szakmailag indokolható. Kényelmi dolgokat ne vegyük!

Júli 31-ig lehet költségvetést módosítani. Részletezettet bekérték,
nem volt visszajelzés.

Laborköltség,  Dinamikus beszerzési portálon? Lassú és időben.

Fogunk kapni egy levelet, hogy elfogadják a költségvetést.

Projektre terhelés alapja és %-a.

Szakmai vezető, kutató, munkatárs, technikus. Projekt adminisztrátort is beírhatunk.
Bidló adatrögzítés és mérést ad!

Feladatokat kitölteni és visszaküldeni. Móni október 31-ig van.
