#+TITLE: Minden projekttel megbeszélés

Jelen: Gazdaságiból és dékániból is és projekt vezetők

Önállóan működni nem képes eszközök.

Sipos Gyuri gondok.

Eszti szerint nem jött semmi Móninak. Különböző felületekre hogyan jelentkezett be.

* Andi
Szakmai rész?

Tímár Andiék kezelik a pályázatot. Személyi ügy Juditnál.
Dologit más intézi.

Fluentákat ők indítanák. TKP. Andin keresztül.

Személyi ügy. 2022-óta nincs AM támogatás elszámoló. Szakmai beszámoló bekérését
a többletes, bekérik. Külön-külön elkülöníthető.

Többletszerződés összeg és idő. Űrlapszerűen kitölteni. 5000 karakteres beszámoló.

Ahogy végezte a feladatát. ERTI megütközött. Szakmai feladat meghatározás kifejtése.

Szakmai vezető jóváhagyása után lehet jóváhagyni.

Bérbeszámítás, munkavezető.

Munkaköri feladat, munkakörön kívülit elkülöníteni. Valahogy legyen
elkülönítve.  Ne tünjön ugyan annak a két feladat. Többletfeladat
eldönteni, ami nem munkaköri kötelessége.

Projektszerződéshez igazodik a program.

Szerződések aktuálisak. HR tervet kérnek, körülbelül mit tervezünk.
Táppénz és szabadság nem elszámolhatól

Tavaly minden kifizetés megtörnént.

A 6. hó és nyolcadik hóval végeznek. Karácsony előtt lenne kifizetés, rész kifizetés?

Pénz még nincs itt. Feladat elvégezve.

Mónival nyáron többlet, szemeszter feladat mehet.

Nincs pénz és nincs HR terv. Ha lejár a végén.

Nekünk BorderEye-al sem esik egybe, Szeptembertől megy a bérráterhelés
és nyáron a többletfeladat.

* HR

HR tervet szakmai részfeladat, személy, mintatáblát
küldenek. Átkönyvelést megcsinálni, hogy rákerüljön a pénzügyi
központban.

Andiék fluentát indítanak. Munkaköri + többletes.

ERTI? Verebélyi Hajnival leegyeztetik Andiék, írjuk be őket az HR
táblába.

HR táblát kiküldik ma, még a jövő hétre. Hétfőre kellene! A fluentákat
elindítják.


December 15-ig tudnak. Dec. 1-re elmenjen.

KarbonKreditben megjött szerződés.

emk-gazdasagi@uni-sopron.hu lesz email.

Vadgazdák külön csinálgatják. Csepregi-Rimóczi és Tari Tomi külön
leülnek. Nem akarják megakasztani, szépen csinálják. Nem ezzel
kellene (admin) foglalkozni.

Kollégának nem lesz idén kifizetés, hallgatónak igen. Egy összegbe
tervezzük a kifizetést, Egy hónappal zárás előtt. Többlettel
tudunk módosítani.

Irattárolás mit-hol?

* Beszerzés
Anita csinálja, TKP erdőlab és BorderEye-ban csinálja.

Egyetemi beszerzési tervet összenézni a szerződésekkel. Kincses Zsolt
és szakmai vezetők és Anita. Fluenta Anitával indult.

Beszerzési tervbe rosszul lett beírva a pénzügyi központ.

Anita bekéri a beszerzési tervet. Egyszerre kellene végig gondolni
a beszerzésnél. Mi az amit indíthatnánk?

Fluenta kész, műszaki specifikáció, honnan szeretném beszerezni?

Anita sablon, negyedéves ütemezés, műszaki spec, legalább 3 cég, 200 e
Ft előtti.

Rezsi most került be. Kihez kerül a rezsi. Elszámolható. valamit lead
az Egyetem. Projektben bent volt a gázszámla. Kitalálják, hogy mi legyen?

Minden pályázatból kezdünk kiesni, mint alapítványi egyetem.

Horizonban Associate Partner leszünk, nincs költség, adjon feladatot.
És magyarból lesz támogatás. Bért is és önerő alapból. Interreg
stratégiai partnerként nem jár pénz.

Nekem jön a dokumentum.

* Fluenta

Fluenta hogyan menjen? Van egy kari fluenta kérő űrlap. Milyen
központra, hogyan? Hol legyen, ahol szakmailag megfogalmazó? Ki
indítsa? Zsuzsa még nem látja át, ha valami nem megy.

Külön Űrlap az AM-nek. Formsba be tudja írni az oktató? Mikor megy
valaki.

Utazásokra időszakos fluenta. Tankolás viszont egyetemi szabályzat szerint.

Kutatási asszisztensek.

Keret figyelés fontos!

Gond elindul a fluenta, azt visszacsatornázni AM-be. Sarkalatos a
fluenta, hogy forrás rendbe van-e?

Emailben vagy formsban, majd eldöntik Eszterrel. Tudsz forms-ot
megosztani. Zsuzsa megosztja.

Eszteréknek könnyebb a forms. Lehet lesz AM-re.

Formshoz lehet fájlmellékletet feltölteni. Kornél csinálta a formsot.

Bevennék a fluentába a kollégákat. Kétszer van jóváhagyva.

* Hallgató

Hallgatói szerződés, formanyomtatvány sablon.

Kapcsolattartónál legyen elérhetőség. Kötelező névviselés van.
Titulus a neveknél legyen. A külsők miatt.

Ki érkezteti a számlát? EMK! Záradékolást Anita csinálja.

Bérátterhelés feladatot és időszakot, embert. Munkaköri leírás
kiegészítést ki csinálja? Mindenképpen kell, amibe benne van, hogy
ezzel foglalkozik. Először bérbeszámítés utána többlet.

A projektnek maradjon a védhető logikája.

Minden projektben minden kolléga. Sokan vannak bevonva kicsivel,
mégsem kevés rendes munkával.

Ellenőr a szakmai részhez nem ért. Az adminisztráció legyen rendben!

Minimális korrekció lesz a bérráterhelésben a százalékok miatt!

TimeSheet? Többletes szerződést HR készíti? Hallgatói megbízást mi
csináljuk.  Ha nem akarunk külön jelentést írni, nem beszámolót!
Jogilag 12 órát dolgozni, mem küldünk vasárnap emailt. Ha rosszul
csinálsz valamit nem tudsz elszámolni.

Eszközök, felelős, leltározás és folyamatos rendelkezésre
állás. Tárgyieszköz a projektre rendben. Kinél az eszközt, személyhez
rendelni. Ami tárgyi eszköz kartonba bekerül. Kis anyagokról kellhet kép.

Mikor selejtezhető? Fenntartási idő végén?

* Kérdés
Milyen számot írhatunk a publikációval? Címet írjuk be. Magyar cím a hivatalos.

Hallgató?
